development:
  adapter: postgresql
  encoding: unicode
  database: my_scheduler
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: my_scheduler_test
  pool: 5
  username: postgres
  password: postgres
